V2.DocVerifier.Web/Models/ErrorViewModel.cs
namespace V2.DocVerifier.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public string ErrorMessage { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

V2.DocVerifier.Web/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using V2.DocVerifier.Models;

namespace V2.DocVerifier.Web.Controllers
{
    [Route("/Error")]
    public class ErrorController : Controller
    {
        /// <summary>
        /// Generic action method which will be invoked incase of any exception across the application
        /// </summary>
        /// <returns>IActionResult</returns>
        [AllowAnonymous]
        public IActionResult Index()
        {
            var exceptionDetails = HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            if (exceptionDetails?.Error != null)
            {
                return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, ErrorMessage = exceptionDetails.Error.Message });
            }
            return View("Error");
        }
    }
}

V2.DocVerifier.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using V2.DocVerifier.Models;
using V2.DocVerifier.Services.UI.Interfaces;

namespace V2.DocVerifier.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDocVerifier _docVerifier;

        public HomeController(IDocVerifier docVerifier)
        {
            _docVerifier = docVerifier;
        }

        /// <summary>
        /// UI for uploading the file for extraction process.
        /// </summary>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Action method to extract the data then redirect the user to the listing page.
        /// </summary>
        /// <param name="model">GeminiRequest</param>
        /// <returns>IActionResult</returns>
        [HttpPost]
        public async Task<IActionResult> Index(GeminiRequest model)
        {
            HttpContext.Session.Set<List<GeminiResponse>>("docResponse", await _docVerifier.ExecuteAsync(model));
            return RedirectToAction("ListDocuments");
        }

        /// <summary>
        /// Listing the document extracted data based on the page.
        /// </summary>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> ListDocuments()
        {
            var model = HttpContext.Session.Get<List<GeminiResponse>>("docResponse");
            return View(model);
        }

        /// <summary>
        /// Action method to display the extracted data on the screen.
        /// </summary>
        /// <param name="docType">string</param>
        /// <param name="pageNumber">int</param>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> DocumentDetails(string docType, int pageNumber)
        {
            var responseData = HttpContext.Session.Get<List<GeminiResponse>>("docResponse");
            var model = responseData.Where(data=> data.DocumentType == docType && data.PageNumber == pageNumber.ToString()).FirstOrDefault();
            return View(model);
        }

        /// <summary>
        /// List the 37 pay stub data.
        /// </summary>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> ListPayStubResults()
        {
            var model = await _docVerifier.GetPayStubResultsAsync();
            return View(model);
        }

        /// <summary>
        /// Load the paystub results
        /// </summary>
        /// <param name="fileName">string</param>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> LoadPayStub(string fileName)
        {
            HttpContext.Session.Set<List<GeminiResponse>>("docResponse", await _docVerifier.LoadPayStubAsync(fileName));
            return RedirectToAction("ListDocuments");
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

V2.DocVerifier.Web/Controllers/ValidateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using V2.DocVerifier.Models;
using V2.DocVerifier.Services.UI.Interfaces;

namespace V2.DocVerifier.Web.Controllers
{
    public class ValidateController : Controller
    {
        private readonly ILogger<ValidateController> _logger;
        private readonly IDocValidator _docValidator;

        public ValidateController(ILogger<ValidateController> logger, IDocValidator docValidator)
        {
           _logger = logger;
            _docValidator = docValidator;
        }

        /// <summary>
        /// UI for uploading the file for extraction process.
        /// </summary>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Action method to extract the data then redirect the user to the listing page.
        /// </summary>
        /// <param name="model">GeminiRequest</param>
        /// <returns>IActionResult</returns>
        [HttpPost]
        public async Task<IActionResult> Index(GeminiRequest model)
        {
            HttpContext.Session.Set<List<GeminiDestinationData>>("docValidateResponse", await _docValidator.ValidateAsync(model));
            return RedirectToAction("ListDocuments");
        }

        /// <summary>
        /// Listing the document extracted data based on the page.
        /// </summary>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> ListDocuments()
        {
            var model = HttpContext.Session.Get<List<GeminiDestinationData>>("docValidateResponse");
            return View(model);
        }

        /// <summary>
        /// Action method to display the extracted data on the screen.
        /// </summary>
        /// <param name="docType">string</param>
        /// <param name="pageNumber">int</param>
        /// <returns>IActionResult</returns>
        [HttpGet]
        public async Task<IActionResult> DocumentDetails(string docType, int pageNumber)
        {
            var responseData = HttpContext.Session.Get<List<GeminiDestinationData>>("docValidateResponse");
            var model = responseData.Where(data=> data.DocumentType == docType && data.PageNumber == pageNumber.ToString()).FirstOrDefault();
            return View(model);
        }
    }
}

V2.DocVerifier.Web/Views/Home/DocumentDetails.cshtml
@using V2.DocVerifier.Models;
@model GeminiResponse;

@{
    ViewData["Title"] = "Document Details";
}

<div class="call-center-wrap">
    <div class="call-center-form">
        <div class="header-line">
            <h2>Document Details</h2>
        </div>

        <div class="row">
            <div class="col">
                <div class="text-end">
                    <button class="btn btn-default btn-back" type="button" id="btnLegalBack"><i class="fa-solid fa-chevron-left"></i> Back</button> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home"><i class="fal fa-plus"></i> New Document</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home/ListPayStubResults">Paystub Results</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Validate/Index">Paystub Validator</a>
                </div>
            </div>
        </div>

        <div class="row" width="100%">
            <div class="col-md-4 bg-light border" style="overflow-y: scroll; height:800px;">
                <table id="tblsearch" width="100%" class="support-case-table table dt-responsive mb-4">
                    <thead>
                        <tr>
                            <th>Element</th>
                            <th>Value</th>
                            <th>Override</th>
                            <th>Accuracy %</th>
                        </tr>
                    </thead>

                    @{
                        foreach (var item in Model.Elements)
                        {
                            var _result = item.Confidence_Score * 100;
                            <tr onmouseover="plotCordinate(@item.X,@item.Y, @item.Height, @item.Width)" onmouseout="clearPlot(@item.X,@item.Y, @item.Height, @item.Width)">
                                <td>@item.Label</td>
                                <td>@item.Value</td>
                                <td><input type=text value="@item.Value" /></td>
                                <td>@_result</td>
                            </tr>
                        }
                    }
                </table>
            </div>
            <div class="col-md-8 bg-light border">
                <div className="canvas-section flex-grow-1 bg-light h-100 overflow-auto hide-scrollbar border rounded d-flex justify-content-center">
                    <canvas id="myCanvas" className="bg-white" />
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/dist/components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.min.js" type="text/javascript"></script>
    <script src="~/dist/components/filepond/dist/filepond.min.js"></script>
    <script src="~/dist/components/filepond/jquery-filepond/filepond.jquery.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="~/js/document_verifier/docverifier.js" type="text/javascript" asp-append-version="true"></script>
    <script src="~/js/document_verifier/imageDetails.js" type="text/javascript" asp-append-version="true"></script>
    <script>
        loadImage(@Model.ImageWidth, @Model.ImageHeight, @Html.Raw(Json.Serialize(@Model.ImageContent)));
    </script>
}

V2.DocVerifier.Web/Views/Home/Index.cshtml
@using V2.DocVerifier.Models;
@model GeminiRequest;

@{
    ViewData["Title"] = "Home Page";
}

@section styles {
    <link href="~/dist/components/filepond/dist/filepond.min.css" media="all" rel="stylesheet" type="text/css" />
}

<div class="call-center-wrap">
    <div class="call-center-form">
        <div class="header-line">
            <h2>Document Verifier Request</h2>
        </div>

        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home/ListPayStubResults">Paystub Results</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Validate/Index">Paystub Validator</a>
                </div>
            </div>
        </div>


        <div class="form-wrap">
            <form asp-action="Index" method="post" asp-controller="Home" id="document-verifier-submit" autocomplete="off" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group case-file-upload">
                            <label asp-for="FormFile" class="control form-label"></label>
                            <input type="file" asp-for="FormFile" multiple />
                            <label asp-validation-for="FormFile" class="error"></label>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="form-action">
                    <div class="btn-right-wrap">
                        <button class="btn btn-primary save-btn" type="submit" id="btnLegalSave"> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/dist/components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.min.js" type="text/javascript"></script>
    <script src="~/dist/components/filepond/dist/filepond.min.js"></script>
    <script src="~/dist/components/filepond/jquery-filepond/filepond.jquery.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="~/js/document_verifier/docverifier.js" type="text/javascript" asp-append-version="true"></script>

}

V2.DocVerifier.Web/Views/Home/Index_old.cshtml
@using V2.DocVerifier.Models;
@model FileUpload;

@{
    ViewData["Title"] = "Home Page";
}

<h1>Gemini Doc Verifier</h1>

<form enctype="multipart/form-data" method="post">
    <table>
        <tr>
            <td>
                <dl>
                    <dt>
                        <label asp-for="FormFile"></label>
                    </dt>
                    <dd>
                        <input asp-for="FormFile" type="file" />
                        <span asp-validation-for="FormFile"></span>
                    </dd>
                </dl>

                <input asp-page-handler="Upload" class="btn" type="submit" value="Upload" />
            </td>
            <td>
                @if (Model != null && !string.IsNullOrEmpty(Model.Json))
                {
                    <textarea id="completeJSON" rows="20" cols="80">@Model.Json</textarea>
                }
            </td>
        </tr>
    </table>

    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <img src="" class="imagepreview" style="width: 100%;height:100%">
                </div>
            </div>
        </div>
    </div>

    @if (Model != null && Model.FormResponse != null)
    {
        <div class="accordion" id="accordionExample">
            @{
                var _headerCounter = 1;
            }

            @foreach (var document in Model.FormResponse)
            {
                var _headerId = "";
                var _headerText = "";
                var _pageNumber = "";
                try
                {
                    _headerId = $"header{document.documentType}";
                    _headerText = $"{document.documentType}";
                }
                catch
                {
                }


                if (string.IsNullOrEmpty(_headerText))
                {
                    try
                    {
                        _headerId = $"header{document.document_type}";
                        _headerText = $"{document.document_type}";
                    }
                    catch
                    {
                    }
                }

                try
                {
                    _pageNumber = $"header{document.pageNumber}";
                }
                catch
                {

                }

                if (string.IsNullOrEmpty(_pageNumber))
                {
                    try
                    {
                        _pageNumber = $"header{document.page_number}";
                    }
                    catch
                    {

                    }
                }


                var _itemId = $"pageNumber{_pageNumber}{_headerCounter}";
                var _tablebodyId = $"tableBody{_pageNumber}{_headerCounter}";
                var _pageURL = $"{Model.FilePath}/{document.imageFile}";
                _headerCounter = _headerCounter + 1;
                var _headerValue = _headerText;

                <div class="accordion-item">
                    <h2 class="accordion-header" id="@_headerId">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#@_itemId" aria-expanded="true" aria-controls="@_itemId">
                            @_headerValue.ToUpper() # Page Number : @document.page_number
                        </button>
                    </h2>
                    <div id="@_itemId" class="accordion-collapse collapse show" aria-labelledby="@_headerId" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">Key</th>
                                                        <th scope="col">Value</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="@_tablebodyId">
                                                    <tr>
                                                        <td>This is a test message</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                        <td>
                                            <textarea hidden id="json" rows="20" cols="80" data-to-be-parsed data-to-be-render-control="@_tablebodyId">@document</textarea>
                                            <a href="#" class="pop"><img src="@_pageURL" width="400px" height="600px" /></a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</form>

@section Scripts {
    <script language="javascript">

        function renderTable()
        {
            var _textAreaControl = document.querySelectorAll('[data-to-be-parsed]');
            _textAreaControl.forEach(function (item){
            var _tbodyControlName = item.attributes["data-to-be-render-control"].value;
            var _tbodyControl = document.getElementById(_tbodyControlName);

            var _json = JSON.parse(item.value);
            var _control_string = "";
            for(const key in _json)
            {
                if(_json[key] != undefined && typeof(_json[key]) != "object")
                {
                    _control_string = _control_string + "<tr><td>" + key + "</td><td>" + _json[key] + "</td></tr>";
                }
                else
                {
                    _control_string = _control_string + extractData(key, _json[key])
                }
            }
            _tbodyControl.innerHTML = _control_string;
            });
        }

        function extractData(key, jsonObject)
        {
            var _control_string = "";
            for(const innerKey in jsonObject)
            {
                if(jsonObject[innerKey] != undefined && typeof(jsonObject[innerKey]) != "object")
                {
                    _control_string = _control_string + "<tr><td>" + key +"_" + innerKey + "</td><td>" + jsonObject[innerKey] + "</td></tr>";
                }
                else{
                    _control_string = _control_string + extractData(key + "_" + innerKey, jsonObject[innerKey])
                }
            }
            return _control_string;
        }

            $(function() {
                $('.pop').on('click', function() {
                    $('.imagepreview').attr('src', $(this).find('img').attr('src'));
                    $('#imagemodal').modal('show');
                });
        });

        renderTable();
    </script>
}

V2.DocVerifier.Web/Views/Home/ListDocuments.cshtml
@using V2.DocVerifier.Models;
@model List<GeminiResponse>;

@{
    ViewData["Title"] = "List Documents";
}

<div class="call-center-wrap">
    <div class="call-center-form">
        <div class="header-line">
            <h2>List Document Types</h2>
        </div>

        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home"><i class="fal fa-plus"></i> New Document</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home/ListPayStubResults">Paystub Results</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Validate/Index">Paystub Validator</a>
                </div>
            </div>
        </div>

        <div class="form-wrap">
            <div id="searResultPan">
                <table id="tblsearch" width="100%" class="support-case-table table dt-responsive mb-4">
                    <thead>
                        <tr>
                            <th>Document Type</th>
                            <th>File Name</th>
                            <th>File Type</th>
                            <th>Accuracy %</th>
                            <th>Is Document Fraud</th>
                            <th>Is Document Duplicate</th>
                        </tr>
                    </thead>

                    @{
                        foreach (var item in Model)
                        {
                            var _result = item.ConfidenceScore * 100;
                            <tr>
                                <td><a href="/home/documentDetails?docType=@item.DocumentType&pageNumber=@item.PageNumber"> @item.DocumentType </a></td>
                                <td>@item.FileName</td>
                                <td>@item.ContentType</td>
                                <td>@_result</td>
                                <td>@item.IsFraudDocument</td>
                                <td>@item.IsReissued</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/dist/components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.min.js" type="text/javascript"></script>
    <script src="~/dist/components/filepond/dist/filepond.min.js"></script>
    <script src="~/dist/components/filepond/jquery-filepond/filepond.jquery.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="~/js/document_verifier/docverifier.js" type="text/javascript" asp-append-version="true"></script>
}

V2.DocVerifier.Web/Views/Home/ListPayStubResults.cshtml
@using V2.DocVerifier.Models;
@model List<GeminiPayStubResult>;

@{
    ViewData["Title"] = "Paystub Results";
}

<div class="call-center-wrap">
    <div class="call-center-form">
        <div class="header-line">
            <h2>Paystub Results</h2>
        </div>

        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home"><i class="fal fa-plus"></i> New Document</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Validate/Index">Paystub Validator</a>
                </div>
            </div>
        </div>

        <div class="form-wrap">
            <div id="searResultPan">
                <table id="tblsearch" width="100%" class="support-case-table table dt-responsive mb-4">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>File Type</th>
                            <th>File Name</th>
                        </tr>
                    </thead>

                    @{
                        foreach (var item in Model)
                        {
                            <tr>
                                <td><a href="/Home/LoadPayStub?fileName=@item.FileName">@item.Name</a></td>
                                <td>@item.Type</td>
                                <td>@item.FileName</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/dist/components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.min.js" type="text/javascript"></script>
    <script src="~/dist/components/filepond/dist/filepond.min.js"></script>
    <script src="~/dist/components/filepond/jquery-filepond/filepond.jquery.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="~/js/document_verifier/docverifier.js" type="text/javascript" asp-append-version="true"></script>
}

V2.DocVerifier.Web/Views/Shared/_Layout_old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - V2.DocVerifier.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/V2.DocVerifier.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">V2.DocVerifier.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - V2.DocVerifier.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

V2.DocVerifier.Web/Views/Validate/Index.cshtml
@using V2.DocVerifier.Models;
@model GeminiRequest;

@{
    ViewData["Title"] = "Home Page";
}

@section styles {
    <link href="~/dist/components/filepond/dist/filepond.min.css" media="all" rel="stylesheet" type="text/css" />
}

<div class="call-center-wrap">
    <div class="call-center-form">
        <div class="header-line">
            <h2>Document Validator Request</h2>
        </div>

        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home"><i class="fal fa-plus"></i> New Document</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary save-btn text-bold load-add" href="/Home/ListPayStubResults">Paystub Results</a>
                </div>
            </div>
        </div>


        <div class="form-wrap">
            <form asp-action="Index" method="post" asp-controller="Validate" id="document-verifier-submit" autocomplete="off" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group case-file-upload">
                            <label asp-for="FormFile" class="control form-label"></label>
                            <input type="file" asp-for="FormFile" multiple />
                            <label asp-validation-for="FormFile" class="error"></label>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="form-action">
                    <div class="btn-right-wrap">
                        <button class="btn btn-primary save-btn" type="submit" id="btnLegalSave"> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/dist/components/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.min.js" type="text/javascript"></script>
    <script src="~/dist/components/filepond/dist/filepond.min.js"></script>
    <script src="~/dist/components/filepond/jquery-filepond/filepond.jquery.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>
    <script src="~/dist/components/filepond/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="~/js/document_verifier/docverifier.js" type="text/javascript" asp-append-version="true"></script>

}